server/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('seriados/', include('seriados.urls')),
]

server/seriados/urls.py
from django.urls import path, re_path, include, register_converter
from django.views.generic import TemplateView

from . import views

app_name = 'seriados'

urlpatterns = [
    path('series/', views.series_list, name='series_list'),
    path('series/<int:pk>/', views.series_details, name='series_details'),

    path('episodios/', views.episodio_list, name='episodio_list'),
    path('episodios/<int:pk>/', views.episodio_details, name='episodio_details'),

    path('episodios/nota/<str:nota>/', views.episodio_nota_list, name='episodio_nota_list'),

    path('sobre/', TemplateView.as_view(template_name="about.html"), name='about'),
    path('contato/', views.Contact.as_view(), name='contact'),

    path('', views.HomeView.as_view(), name='home'),

    path('temporadas/', views.TemporadaListView.as_view(), name='temporadas'),

]

server/seriados/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _

class Serie(models.Model):
    nome = models.CharField(max_length=70)

    def __str__(self):
        return self.nome

class Temporada(models.Model):
    numero = models.IntegerField()
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.serie.nome}: {self.numero}"

class Episodio(models.Model):
    data = models.DateField()
    titulo = models.CharField(max_length=200, verbose_name="Título")
    temporada = models.ForeignKey(Temporada, on_delete=models.CASCADE)

    def __str__(self):
        nome_serie = self.temporada.serie.nome
        return f"{nome_serie} - {self.temporada.numero}: {self.titulo}"

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('seriados: episodio_detalhes', kwargs={'pk': self.pk})

    def eh_antigo(self):
        import datetime
        if self.data < datetime.date(2000, 1, 1):
            return True
        return False

class Revisor(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    reviews_episodios = models.ManyToManyField(Episodio, through='ReviewEpisodio')

class ReviewEpisodio(models.Model):
    NOTA_A = 'A'
    NOTA_B = 'B'
    NOTA_C = 'C'
    NOTAS_CHOICES = [
        (NOTA_A, _("Excelente")),
        (NOTA_B, _("Bom")),
        (NOTA_C, _("Ruim"))
    ]
    episodio = models.ForeignKey(Episodio, on_delete=models.CASCADE)
    revisor = models.ForeignKey(Revisor, on_delete=models.CASCADE)
    nota = models.CharField(
        max_length = 1,
        choices = NOTAS_CHOICES,
        default = NOTA_B
    )

server/seriados/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.forms.models import model_to_dict
from .models import Serie, Temporada, Episodio
from django.views import View
from django.views.generic import TemplateView, ListView

def prepare_data_list(objects, fields_name):
    labels = list()
    for field_name in fields_name:
        field = objects.model._meta.get_field(field_name)
        labels.append(field.verbose_name)

    rows = list()
    for _object in objects:
        row = dict()
        rows.append(row)
        row['pk'] = _object.pk
        row['data'] = list()
        for field_name in fields_name:
            row['data'].append(getattr(_object, field_name))
    return labels, rows

def prepare_data_detail(_object, fields_name):
    data = model_to_dict(_object)
    rows = list()
    for field_name in fields_name:
        field = _object._meta.get_field(field_name)
        rows.append({'label': field.verbose_name, 'value': data[field_name]})
    return rows

def episodio_list(request):
    search = request.GET.get('search', "")
    objects = Episodio.objects.filter(titulo__contains=search)
    labels, rows = prepare_data_list(objects, ['titulo', 'data'])
    context = {
        'title': "Episódios",
        'labels': labels,
        'rows': rows,
        'detail_url': 'seriados:episodio_details',
    }
    return render(request, 'list.html', context)

def episodio_nota_list(request, nota):
    objects = Episodio.objects.filter(reviewepisodio_nota=nota)
    context = {
        'objects': objects,
        'nota': nota,
    }
    return render(request, 'episodio_nota_list.html', context)

def episodio_details(request, pk):
    _object = get_object_or_404(Episodio, pk=pk)
    context = {
        'title': "Episódio",
        'data': prepare_data_detail(_object, ['titulo', 'data', 'temporada']),
    }
    return render(request, 'details.html', context)

def series_list(request):
    objects = Serie.objects.all()
    labels, rows = prepare_data_list(object, ['nome'])
    context = {
        'title': "Series",
        'labels': labels,
        'rows': rows,
        'detail_url': 'seriados:series_details',
    }
    return render(request, 'list.html', context)

def series_details(request, pk):
    _object = get_object_or_404(Serie, pk=pk)
    context = {
        'title': "Serie",
        'data': prepare_data_detail(_object, ['nome']),
    }
    return render(request, 'details.html', context)

class Contact(TemplateView):
    template_name = 'contact.html'

class HomeView(View):
    def get(self, request):
        return render(request, 'home.html', {})

class TemporadaListView(ListView):
    template_name = 'temporada_list.html'
    model = Temporada

server/seriados/templates/about.html
{% extends "base.html" %}
{% block content %}

    Sistema para cadastro e reviews de Seriados!<br>
    <b>Curso de Especialização em Python para Negócios</b>
    <p><a href="{% url 'seriados:about' %}">Sobre</a></p>

{% endblock %}

server/seriados/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Python para Negócios</title>
        <meta charset="UTF-8">
    </head>
    <body>
        <p>Bem-vindo</p>
        {% block content %}
            <p>Não há nenhum conteúdo aqui!</p>
        {% endblock %}
    </body>
</html>

server/seriados/templates/contact.html
{% extends "base.html" %}
{% block content %}

    <h3>Contato</h3>
    <p><b>email:</b> contato@exemplo.com.br</p>
    <p><a href="{% url 'seriados:contact' %}">Contato</a></p>

{% endblock %}

server/seriados/templates/details.html
{% extends "base.html" %}

{% block content %}
<h1>Detalhes de {{title}}</h1>

{% for row in data %}
    <p><b>{{ row.label }}</b>: {{ row.value }}</p>
{% endfor %}
{% endblock %}

server/seriados/templates/episodio_nota_list.html
{% extends "base.html" %}
{% block content %}

<h1>Lista de Episódios com nota {{ nota }}</h1>

<table>
    <tr><th>titulo</th><th>data</th><th>temporada</th></tr>
{% for obj in objects %}
    <tr>
        <td>{{obj.titulo}}</td>
        <td>{{obj.data}}</td>
        <td>{{obj.temporada.numero}}</td>
    </tr>
{% endfor %}
</table>
{% endblock %}

server/seriados/templates/home.html
{% extends "base.html" %}

{% block content %}

<p><a href="{% url'seriados:home' %}"> Home</a></p>
<p><a href="{% url 'seriados:series_list' %}">Series</a></p>
<p><a href="{% url 'seriados:episodio_list' %}">Episódios</a></p>

<p>
    <a href="{% url 'seriados:episodio_nota_list' nota='A' %}">Episódios Nota A</a>
    <a href="{% url 'seriados:episodio_nota_list' nota='B' %}">Episódios Nota B</a>
    <a href="{% url 'seriados:episodio_nota_list' nota='C' %}">Episódios Nota C</a>
</p>

<p><a href="{% url 'seriados:temporadas' %}">Temporadas</a></p>

<p><a href="{% url 'seriados:about' %}">Sobre</a></p>
<p><a href="{% url 'seriados:contact' %}">Contato</a></p>

<p><a href="{% url 'admin:index' %}">ADMIN</a></p>

<h3>Procurar episódio</h3>
<input id='input_search' type="text" placeholder="Search..">
<button id="btn_search">Procurar Episódio</button>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous">
</script>
<script type="text/javascript">
    $(document).ready(function() {
        $("#btn_search").click(function() {
            search = $("#input_search").val();
            url = '{% url 'seriados:episodio_list' %}' + '?' +
                $.param({search:search});
            window.location.href = url;
        });
    });
</script>
{% endblock %}

server/seriados/templates/list.html
{% extends "base.html" %}

{% block content %}
<h1>Lista de {{title}}</h1>

<table border="1px">
    <tr>
    {% for label in labels %}
        <th>{{ label }}</th>
    {% endfor %}
    <th>Detalhes</th>
    </tr>

    {% for row in rows %}
        <tr>
        {% for value in row.data %}
            <td>{{ value }}</td>
        {% endfor %}
            <td><a href={% url detail_url pk=row.pk %}>Ver...</a></td>
            </tr>
    {% endfor %}
</table>
{% endblock %}

server/seriados/templates/series_list.html
{% extends "base.html" %}
{% block content %}

<h1>Lista de Séries</h1>

{% for series in lista_series %}
    <p>{{ series.nome }}</p>
{% endfor %}
{% endblock %}

server/seriados/templates/temporada_list.html
{% extends "base.html" %}

{% block content %}
<h1>Lista de {{title}}</h1>

<table border="1px">
    <tr>
        <th>Série</th>
        <th>Temporada</th>
    </tr>

    {% for object in object_list %}
    <tr>
        <td>{{ object.serie.nome }}</td>
        <td>{{ object.numero }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}